name: llm_exp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3.0
  - numpy>=1.21.0
  - scikit-learn>=0.24.0
  - pyyaml>=5.4.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pip
  - pip:
    - langchain
    - openai
    - langchain_community
    - llama-index>=0.9.0